--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 17.4 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: custom_code_humantidesclasssubmission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_code_humantidesclasssubmission (
    id bigint NOT NULL,
    tidesclass character varying(50) NOT NULL,
    tidesclass_other character varying(100),
    "timestamp" timestamp with time zone NOT NULL,
    target_id integer NOT NULL,
    tidesclass_subclass_id bigint,
    user_id integer NOT NULL
);


--
-- Name: custom_code_humantidesclasssubmission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_code_humantidesclasssubmission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_code_humantidesclasssubmission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_code_tidesclass; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_code_tidesclass (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: custom_code_tidesclass_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_code_tidesclass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_code_tidesclass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_code_tidesclasssubclass; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_code_tidesclasssubclass (
    id bigint NOT NULL,
    sub_class character varying(100) NOT NULL,
    main_class_id bigint NOT NULL
);


--
-- Name: custom_code_tidesclasssubclass_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_code_tidesclasssubclass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_code_tidesclasssubclass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_code_tidestarget; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_code_tidestarget (
    basetarget_ptr_id integer NOT NULL,
    tidesclass character varying(50) NOT NULL,
    tidesclass_other character varying(100),
    tidesclass_subclass_id bigint,
    auto_tidesclass character varying(50),
    auto_tidesclass_other character varying(100),
    auto_tidesclass_subclass_id bigint,
    human_tidesclass character varying(50),
    human_tidesclass_other character varying(100),
    human_tidesclass_subclass_id bigint,
    auto_tidesclass_prob double precision
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_comment_flags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_comment_flags (
    id integer NOT NULL,
    flag character varying(30) NOT NULL,
    flag_date timestamp with time zone NOT NULL,
    comment_id integer NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: django_comment_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_comment_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_comment_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_comments (
    id integer NOT NULL,
    object_pk character varying(64) NOT NULL,
    user_name character varying(50) NOT NULL,
    user_email character varying(254) NOT NULL,
    user_url character varying(200) NOT NULL,
    comment text NOT NULL,
    submit_date timestamp with time zone NOT NULL,
    ip_address inet,
    is_public boolean NOT NULL,
    is_removed boolean NOT NULL,
    content_type_id integer NOT NULL,
    site_id integer NOT NULL,
    user_id integer
);


--
-- Name: django_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: django_site; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guardian_groupobjectpermission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guardian_groupobjectpermission (
    id integer NOT NULL,
    object_pk character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: guardian_groupobjectpermission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guardian_groupobjectpermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guardian_groupobjectpermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guardian_userobjectpermission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guardian_userobjectpermission (
    id integer NOT NULL,
    object_pk character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    permission_id integer NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: guardian_userobjectpermission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guardian_userobjectpermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guardian_userobjectpermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_alerts_alertstreammessage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_alerts_alertstreammessage (
    id integer NOT NULL,
    topic character varying(500) NOT NULL,
    message_id character varying(50),
    date_shared timestamp with time zone NOT NULL,
    exchange_status character varying(10) NOT NULL
);


--
-- Name: tom_alerts_alertstreammessage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_alerts_alertstreammessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_alerts_alertstreammessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_alerts_brokerquery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_alerts_brokerquery (
    id integer NOT NULL,
    name character varying(500) NOT NULL,
    broker character varying(50) NOT NULL,
    parameters jsonb NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    last_run timestamp with time zone
);


--
-- Name: tom_alerts_brokerquery_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_alerts_brokerquery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_alerts_brokerquery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_common_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_common_profile (
    id integer NOT NULL,
    affiliation character varying(100),
    user_id integer NOT NULL
);


--
-- Name: tom_common_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_common_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_common_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_dataproducts_dataproduct; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_dataproducts_dataproduct (
    id integer NOT NULL,
    product_id character varying(255),
    data character varying(100),
    extra_data text NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    featured boolean NOT NULL,
    observation_record_id integer,
    target_id integer NOT NULL,
    thumbnail character varying(100),
    data_product_type character varying(50) NOT NULL
);


--
-- Name: tom_dataproducts_dataproduct_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_dataproducts_dataproduct_group (
    id integer NOT NULL,
    dataproduct_id integer NOT NULL,
    dataproductgroup_id integer NOT NULL
);


--
-- Name: tom_dataproducts_dataproduct_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_dataproducts_dataproduct_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_dataproducts_dataproduct_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_dataproducts_dataproduct_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_dataproducts_dataproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_dataproducts_dataproduct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_dataproducts_dataproductgroup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_dataproducts_dataproductgroup (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL
);


--
-- Name: tom_dataproducts_dataproductgroup_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_dataproducts_dataproductgroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_dataproducts_dataproductgroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_dataproducts_reduceddatum; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_dataproducts_reduceddatum (
    id integer NOT NULL,
    data_type character varying(100) NOT NULL,
    source_name character varying(100) NOT NULL,
    source_location character varying(200) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    value jsonb NOT NULL,
    data_product_id integer,
    target_id integer NOT NULL
);


--
-- Name: tom_dataproducts_reduceddatum_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_dataproducts_reduceddatum ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_dataproducts_reduceddatum_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_dataproducts_reduceddatum_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_dataproducts_reduceddatum_message (
    id integer NOT NULL,
    reduceddatum_id integer NOT NULL,
    alertstreammessage_id integer NOT NULL
);


--
-- Name: tom_dataproducts_reduceddatum_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_dataproducts_reduceddatum_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_dataproducts_reduceddatum_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_observations_dynamiccadence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_observations_dynamiccadence (
    id integer NOT NULL,
    cadence_strategy character varying(100) NOT NULL,
    cadence_parameters jsonb NOT NULL,
    active boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    observation_group_id integer NOT NULL
);


--
-- Name: tom_observations_dynamiccadence_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_observations_dynamiccadence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_observations_dynamiccadence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_observations_observationgroup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_observations_observationgroup (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL
);


--
-- Name: tom_observations_observationgroup_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_observations_observationgroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_observations_observationgroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_observations_observationgroup_observation_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_observations_observationgroup_observation_records (
    id integer NOT NULL,
    observationgroup_id integer NOT NULL,
    observationrecord_id integer NOT NULL
);


--
-- Name: tom_observations_observationgroup_observation_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_observations_observationgroup_observation_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_observations_observationgroup_observation_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_observations_observationrecord; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_observations_observationrecord (
    id integer NOT NULL,
    facility character varying(50) NOT NULL,
    parameters jsonb NOT NULL,
    observation_id character varying(255) NOT NULL,
    status character varying(200) NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    target_id integer NOT NULL,
    scheduled_end timestamp with time zone,
    scheduled_start timestamp with time zone,
    user_id integer
);


--
-- Name: tom_observations_observationrecord_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_observations_observationrecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_observations_observationrecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_observations_observationtemplate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_observations_observationtemplate (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    facility character varying(50) NOT NULL,
    parameters jsonb NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL
);


--
-- Name: tom_observations_observingstrategy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_observations_observationtemplate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_observations_observingstrategy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_targets_basetarget; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_targets_basetarget (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(100) NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    ra double precision,
    "dec" double precision,
    epoch double precision,
    parallax double precision,
    pm_ra double precision,
    pm_dec double precision,
    galactic_lng double precision,
    galactic_lat double precision,
    distance double precision,
    distance_err double precision,
    mean_anomaly double precision,
    arg_of_perihelion double precision,
    eccentricity double precision,
    lng_asc_node double precision,
    inclination double precision,
    mean_daily_motion double precision,
    semimajor_axis double precision,
    ephemeris_period double precision,
    ephemeris_period_err double precision,
    ephemeris_epoch double precision,
    ephemeris_epoch_err double precision,
    epoch_of_perihelion double precision,
    scheme character varying(50) NOT NULL,
    perihdist double precision,
    epoch_of_elements double precision
);


--
-- Name: tom_targets_target_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_targets_basetarget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_targets_target_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_targets_targetextra; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_targets_targetextra (
    id integer NOT NULL,
    key character varying(200) NOT NULL,
    value text NOT NULL,
    target_id integer NOT NULL,
    bool_value boolean,
    float_value double precision,
    time_value timestamp with time zone
);


--
-- Name: tom_targets_targetextra_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_targets_targetextra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_targets_targetextra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_targets_targetlist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_targets_targetlist (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL
);


--
-- Name: tom_targets_targetlist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_targets_targetlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_targets_targetlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_targets_targetlist_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_targets_targetlist_targets (
    id integer NOT NULL,
    targetlist_id integer NOT NULL,
    basetarget_id integer NOT NULL
);


--
-- Name: tom_targets_targetlist_targets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_targets_targetlist_targets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_targets_targetlist_targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tom_targets_targetname; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tom_targets_targetname (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    created timestamp with time zone NOT NULL,
    target_id integer NOT NULL,
    modified timestamp with time zone NOT NULL
);


--
-- Name: tom_targets_targetname_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tom_targets_targetname ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tom_targets_targetname_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: custom_code_humantidesclasssubmission custom_code_humantidesclasssubmission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_humantidesclasssubmission
    ADD CONSTRAINT custom_code_humantidesclasssubmission_pkey PRIMARY KEY (id);


--
-- Name: custom_code_tidesclass custom_code_tidesclass_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidesclass
    ADD CONSTRAINT custom_code_tidesclass_pkey PRIMARY KEY (id);


--
-- Name: custom_code_tidesclasssubclass custom_code_tidesclasssubclass_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidesclasssubclass
    ADD CONSTRAINT custom_code_tidesclasssubclass_pkey PRIMARY KEY (id);


--
-- Name: custom_code_tidestarget custom_code_tidestarget_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidestarget
    ADD CONSTRAINT custom_code_tidestarget_pkey PRIMARY KEY (basetarget_ptr_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_comment_flags django_comment_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comment_flags
    ADD CONSTRAINT django_comment_flags_pkey PRIMARY KEY (id);


--
-- Name: django_comment_flags django_comment_flags_user_id_comment_id_flag_537f77a7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comment_flags
    ADD CONSTRAINT django_comment_flags_user_id_comment_id_flag_537f77a7_uniq UNIQUE (user_id, comment_id, flag);


--
-- Name: django_comments django_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comments
    ADD CONSTRAINT django_comments_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: guardian_groupobjectpermission guardian_groupobjectperm_group_id_permission_id_o_3f189f7c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobjectperm_group_id_permission_id_o_3f189f7c_uniq UNIQUE (group_id, permission_id, object_pk);


--
-- Name: guardian_groupobjectpermission guardian_groupobjectpermission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobjectpermission_pkey PRIMARY KEY (id);


--
-- Name: guardian_userobjectpermission guardian_userobjectpermi_user_id_permission_id_ob_b0b3d2fc_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectpermi_user_id_permission_id_ob_b0b3d2fc_uniq UNIQUE (user_id, permission_id, object_pk);


--
-- Name: guardian_userobjectpermission guardian_userobjectpermission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectpermission_pkey PRIMARY KEY (id);


--
-- Name: tom_alerts_alertstreammessage tom_alerts_alertstreammessage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_alerts_alertstreammessage
    ADD CONSTRAINT tom_alerts_alertstreammessage_pkey PRIMARY KEY (id);


--
-- Name: tom_alerts_brokerquery tom_alerts_brokerquery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_alerts_brokerquery
    ADD CONSTRAINT tom_alerts_brokerquery_pkey PRIMARY KEY (id);


--
-- Name: tom_common_profile tom_common_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_common_profile
    ADD CONSTRAINT tom_common_profile_pkey PRIMARY KEY (id);


--
-- Name: tom_common_profile tom_common_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_common_profile
    ADD CONSTRAINT tom_common_profile_user_id_key UNIQUE (user_id);


--
-- Name: tom_dataproducts_dataproduct_group tom_dataproducts_datapro_dataproduct_id_dataprodu_4af8fe70_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct_group
    ADD CONSTRAINT tom_dataproducts_datapro_dataproduct_id_dataprodu_4af8fe70_uniq UNIQUE (dataproduct_id, dataproductgroup_id);


--
-- Name: tom_dataproducts_dataproduct_group tom_dataproducts_dataproduct_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct_group
    ADD CONSTRAINT tom_dataproducts_dataproduct_group_pkey PRIMARY KEY (id);


--
-- Name: tom_dataproducts_dataproduct tom_dataproducts_dataproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct
    ADD CONSTRAINT tom_dataproducts_dataproduct_pkey PRIMARY KEY (id);


--
-- Name: tom_dataproducts_dataproduct tom_dataproducts_dataproduct_product_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct
    ADD CONSTRAINT tom_dataproducts_dataproduct_product_id_key UNIQUE (product_id);


--
-- Name: tom_dataproducts_dataproductgroup tom_dataproducts_dataproductgroup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproductgroup
    ADD CONSTRAINT tom_dataproducts_dataproductgroup_pkey PRIMARY KEY (id);


--
-- Name: tom_dataproducts_reduceddatum_message tom_dataproducts_reduced_reduceddatum_id_alertstr_2428f0c2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_reduceddatum_message
    ADD CONSTRAINT tom_dataproducts_reduced_reduceddatum_id_alertstr_2428f0c2_uniq UNIQUE (reduceddatum_id, alertstreammessage_id);


--
-- Name: tom_dataproducts_reduceddatum_message tom_dataproducts_reduceddatum_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_reduceddatum_message
    ADD CONSTRAINT tom_dataproducts_reduceddatum_message_pkey PRIMARY KEY (id);


--
-- Name: tom_dataproducts_reduceddatum tom_dataproducts_reduceddatum_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_reduceddatum
    ADD CONSTRAINT tom_dataproducts_reduceddatum_pkey PRIMARY KEY (id);


--
-- Name: tom_observations_dynamiccadence tom_observations_dynamiccadence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_dynamiccadence
    ADD CONSTRAINT tom_observations_dynamiccadence_pkey PRIMARY KEY (id);


--
-- Name: tom_observations_observationgroup_observation_records tom_observations_observa_observationgroup_id_obse_ffa0ae3c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationgroup_observation_records
    ADD CONSTRAINT tom_observations_observa_observationgroup_id_obse_ffa0ae3c_uniq UNIQUE (observationgroup_id, observationrecord_id);


--
-- Name: tom_observations_observationgroup_observation_records tom_observations_observationgroup_observation_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationgroup_observation_records
    ADD CONSTRAINT tom_observations_observationgroup_observation_records_pkey PRIMARY KEY (id);


--
-- Name: tom_observations_observationgroup tom_observations_observationgroup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationgroup
    ADD CONSTRAINT tom_observations_observationgroup_pkey PRIMARY KEY (id);


--
-- Name: tom_observations_observationrecord tom_observations_observationrecord_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationrecord
    ADD CONSTRAINT tom_observations_observationrecord_pkey PRIMARY KEY (id);


--
-- Name: tom_observations_observationtemplate tom_observations_observingstrategy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationtemplate
    ADD CONSTRAINT tom_observations_observingstrategy_pkey PRIMARY KEY (id);


--
-- Name: tom_targets_basetarget tom_targets_target_name_b9330b11_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_basetarget
    ADD CONSTRAINT tom_targets_target_name_b9330b11_uniq UNIQUE (name);


--
-- Name: tom_targets_basetarget tom_targets_target_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_basetarget
    ADD CONSTRAINT tom_targets_target_pkey PRIMARY KEY (id);


--
-- Name: tom_targets_targetextra tom_targets_targetextra_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetextra
    ADD CONSTRAINT tom_targets_targetextra_pkey PRIMARY KEY (id);


--
-- Name: tom_targets_targetextra tom_targets_targetextra_target_id_key_375dc83f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetextra
    ADD CONSTRAINT tom_targets_targetextra_target_id_key_375dc83f_uniq UNIQUE (target_id, key);


--
-- Name: tom_targets_targetlist tom_targets_targetlist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetlist
    ADD CONSTRAINT tom_targets_targetlist_pkey PRIMARY KEY (id);


--
-- Name: tom_targets_targetlist_targets tom_targets_targetlist_t_targetlist_id_target_id_da532a88_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetlist_targets
    ADD CONSTRAINT tom_targets_targetlist_t_targetlist_id_target_id_da532a88_uniq UNIQUE (targetlist_id, basetarget_id);


--
-- Name: tom_targets_targetlist_targets tom_targets_targetlist_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetlist_targets
    ADD CONSTRAINT tom_targets_targetlist_targets_pkey PRIMARY KEY (id);


--
-- Name: tom_targets_targetname tom_targets_targetname_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetname
    ADD CONSTRAINT tom_targets_targetname_name_key UNIQUE (name);


--
-- Name: tom_targets_targetname tom_targets_targetname_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetname
    ADD CONSTRAINT tom_targets_targetname_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: custom_code_humantidesclas_tidesclass_subclass_id_36d7bd3a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_code_humantidesclas_tidesclass_subclass_id_36d7bd3a ON public.custom_code_humantidesclasssubmission USING btree (tidesclass_subclass_id);


--
-- Name: custom_code_humantidesclasssubmission_target_id_dda0fc14; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_code_humantidesclasssubmission_target_id_dda0fc14 ON public.custom_code_humantidesclasssubmission USING btree (target_id);


--
-- Name: custom_code_humantidesclasssubmission_user_id_97454e02; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_code_humantidesclasssubmission_user_id_97454e02 ON public.custom_code_humantidesclasssubmission USING btree (user_id);


--
-- Name: custom_code_tidesclasssubclass_main_class_id_927c6acb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_code_tidesclasssubclass_main_class_id_927c6acb ON public.custom_code_tidesclasssubclass USING btree (main_class_id);


--
-- Name: custom_code_tidestarget_auto_tidesclass_subclass_id_748471ba; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_code_tidestarget_auto_tidesclass_subclass_id_748471ba ON public.custom_code_tidestarget USING btree (auto_tidesclass_subclass_id);


--
-- Name: custom_code_tidestarget_human_tidesclass_subclass_id_f62f6792; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_code_tidestarget_human_tidesclass_subclass_id_f62f6792 ON public.custom_code_tidestarget USING btree (human_tidesclass_subclass_id);


--
-- Name: custom_code_tidestarget_tidesclass_subclass_id_08d60a8f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_code_tidestarget_tidesclass_subclass_id_08d60a8f ON public.custom_code_tidestarget USING btree (tidesclass_subclass_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_comment_flags_comment_id_d8054933; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comment_flags_comment_id_d8054933 ON public.django_comment_flags USING btree (comment_id);


--
-- Name: django_comment_flags_flag_8b141fcb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comment_flags_flag_8b141fcb ON public.django_comment_flags USING btree (flag);


--
-- Name: django_comment_flags_flag_8b141fcb_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comment_flags_flag_8b141fcb_like ON public.django_comment_flags USING btree (flag varchar_pattern_ops);


--
-- Name: django_comment_flags_user_id_f3f81f0a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comment_flags_user_id_f3f81f0a ON public.django_comment_flags USING btree (user_id);


--
-- Name: django_comments_content_type_id_c4afe962; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comments_content_type_id_c4afe962 ON public.django_comments USING btree (content_type_id);


--
-- Name: django_comments_is_removed_52a03ae3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comments_is_removed_52a03ae3 ON public.django_comments USING btree (is_removed);


--
-- Name: django_comments_object_pk_7fc98e83; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comments_object_pk_7fc98e83 ON public.django_comments USING btree (object_pk);


--
-- Name: django_comments_object_pk_7fc98e83_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comments_object_pk_7fc98e83_like ON public.django_comments USING btree (object_pk varchar_pattern_ops);


--
-- Name: django_comments_site_id_9dcf666e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comments_site_id_9dcf666e ON public.django_comments USING btree (site_id);


--
-- Name: django_comments_submit_date_514ed2d9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comments_submit_date_514ed2d9 ON public.django_comments USING btree (submit_date);


--
-- Name: django_comments_user_id_a0a440a1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_comments_user_id_a0a440a1 ON public.django_comments USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: guardian_gr_content_ae6aec_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_gr_content_ae6aec_idx ON public.guardian_groupobjectpermission USING btree (content_type_id, object_pk);


--
-- Name: guardian_groupobjectpermission_content_type_id_7ade36b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_groupobjectpermission_content_type_id_7ade36b8 ON public.guardian_groupobjectpermission USING btree (content_type_id);


--
-- Name: guardian_groupobjectpermission_group_id_4bbbfb62; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_groupobjectpermission_group_id_4bbbfb62 ON public.guardian_groupobjectpermission USING btree (group_id);


--
-- Name: guardian_groupobjectpermission_permission_id_36572738; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_groupobjectpermission_permission_id_36572738 ON public.guardian_groupobjectpermission USING btree (permission_id);


--
-- Name: guardian_us_content_179ed2_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_us_content_179ed2_idx ON public.guardian_userobjectpermission USING btree (content_type_id, object_pk);


--
-- Name: guardian_userobjectpermission_content_type_id_2e892405; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_userobjectpermission_content_type_id_2e892405 ON public.guardian_userobjectpermission USING btree (content_type_id);


--
-- Name: guardian_userobjectpermission_permission_id_71807bfc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_userobjectpermission_permission_id_71807bfc ON public.guardian_userobjectpermission USING btree (permission_id);


--
-- Name: guardian_userobjectpermission_user_id_d5c1e964; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guardian_userobjectpermission_user_id_d5c1e964 ON public.guardian_userobjectpermission USING btree (user_id);


--
-- Name: tom_dataproducts_dataproduct_group_dataproduct_id_530f0f37; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_dataproduct_group_dataproduct_id_530f0f37 ON public.tom_dataproducts_dataproduct_group USING btree (dataproduct_id);


--
-- Name: tom_dataproducts_dataproduct_group_dataproductgroup_id_75dd81e2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_dataproduct_group_dataproductgroup_id_75dd81e2 ON public.tom_dataproducts_dataproduct_group USING btree (dataproductgroup_id);


--
-- Name: tom_dataproducts_dataproduct_observation_record_id_95bdba8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_dataproduct_observation_record_id_95bdba8b ON public.tom_dataproducts_dataproduct USING btree (observation_record_id);


--
-- Name: tom_dataproducts_dataproduct_product_id_fb5322f9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_dataproduct_product_id_fb5322f9_like ON public.tom_dataproducts_dataproduct USING btree (product_id varchar_pattern_ops);


--
-- Name: tom_dataproducts_dataproduct_target_id_dce26955; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_dataproduct_target_id_dce26955 ON public.tom_dataproducts_dataproduct USING btree (target_id);


--
-- Name: tom_dataproducts_reducedda_alertstreammessage_id_516add5f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_reducedda_alertstreammessage_id_516add5f ON public.tom_dataproducts_reduceddatum_message USING btree (alertstreammessage_id);


--
-- Name: tom_dataproducts_reduceddatum_data_product_id_714545fa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_reduceddatum_data_product_id_714545fa ON public.tom_dataproducts_reduceddatum USING btree (data_product_id);


--
-- Name: tom_dataproducts_reduceddatum_message_reduceddatum_id_c9d20296; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_reduceddatum_message_reduceddatum_id_c9d20296 ON public.tom_dataproducts_reduceddatum_message USING btree (reduceddatum_id);


--
-- Name: tom_dataproducts_reduceddatum_target_id_7112fa36; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_reduceddatum_target_id_7112fa36 ON public.tom_dataproducts_reduceddatum USING btree (target_id);


--
-- Name: tom_dataproducts_reduceddatum_timestamp_b02b8446; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_dataproducts_reduceddatum_timestamp_b02b8446 ON public.tom_dataproducts_reduceddatum USING btree ("timestamp");


--
-- Name: tom_observations_dynamiccadence_observation_group_id_178fcf19; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_observations_dynamiccadence_observation_group_id_178fcf19 ON public.tom_observations_dynamiccadence USING btree (observation_group_id);


--
-- Name: tom_observations_observati_observationgroup_id_1decf344; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_observations_observati_observationgroup_id_1decf344 ON public.tom_observations_observationgroup_observation_records USING btree (observationgroup_id);


--
-- Name: tom_observations_observati_observationrecord_id_8e121c87; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_observations_observati_observationrecord_id_8e121c87 ON public.tom_observations_observationgroup_observation_records USING btree (observationrecord_id);


--
-- Name: tom_observations_observationrecord_target_id_6e7111f2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_observations_observationrecord_target_id_6e7111f2 ON public.tom_observations_observationrecord USING btree (target_id);


--
-- Name: tom_observations_observationrecord_user_id_517144d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_observations_observationrecord_user_id_517144d8 ON public.tom_observations_observationrecord USING btree (user_id);


--
-- Name: tom_targets_target_name_b9330b11_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_targets_target_name_b9330b11_like ON public.tom_targets_basetarget USING btree (name varchar_pattern_ops);


--
-- Name: tom_targets_targetextra_target_id_c59c68fc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_targets_targetextra_target_id_c59c68fc ON public.tom_targets_targetextra USING btree (target_id);


--
-- Name: tom_targets_targetlist_targets_target_id_6ab078e4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_targets_targetlist_targets_target_id_6ab078e4 ON public.tom_targets_targetlist_targets USING btree (basetarget_id);


--
-- Name: tom_targets_targetlist_targets_targetlist_id_41810969; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_targets_targetlist_targets_targetlist_id_41810969 ON public.tom_targets_targetlist_targets USING btree (targetlist_id);


--
-- Name: tom_targets_targetname_name_bdaef0d6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_targets_targetname_name_bdaef0d6_like ON public.tom_targets_targetname USING btree (name varchar_pattern_ops);


--
-- Name: tom_targets_targetname_target_id_c5dda20c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tom_targets_targetname_target_id_c5dda20c ON public.tom_targets_targetname USING btree (target_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_humantidesclasssubmission custom_code_humantid_target_id_dda0fc14_fk_custom_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_humantidesclasssubmission
    ADD CONSTRAINT custom_code_humantid_target_id_dda0fc14_fk_custom_co FOREIGN KEY (target_id) REFERENCES public.custom_code_tidestarget(basetarget_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_humantidesclasssubmission custom_code_humantid_tidesclass_subclass__36d7bd3a_fk_custom_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_humantidesclasssubmission
    ADD CONSTRAINT custom_code_humantid_tidesclass_subclass__36d7bd3a_fk_custom_co FOREIGN KEY (tidesclass_subclass_id) REFERENCES public.custom_code_tidesclasssubclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_humantidesclasssubmission custom_code_humantid_user_id_97454e02_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_humantidesclasssubmission
    ADD CONSTRAINT custom_code_humantid_user_id_97454e02_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_tidesclasssubclass custom_code_tidescla_main_class_id_927c6acb_fk_custom_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidesclasssubclass
    ADD CONSTRAINT custom_code_tidescla_main_class_id_927c6acb_fk_custom_co FOREIGN KEY (main_class_id) REFERENCES public.custom_code_tidesclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_tidestarget custom_code_tidestar_auto_tidesclass_subc_748471ba_fk_custom_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidestarget
    ADD CONSTRAINT custom_code_tidestar_auto_tidesclass_subc_748471ba_fk_custom_co FOREIGN KEY (auto_tidesclass_subclass_id) REFERENCES public.custom_code_tidesclasssubclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_tidestarget custom_code_tidestar_basetarget_ptr_id_eb84e20a_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidestarget
    ADD CONSTRAINT custom_code_tidestar_basetarget_ptr_id_eb84e20a_fk_tom_targe FOREIGN KEY (basetarget_ptr_id) REFERENCES public.tom_targets_basetarget(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_tidestarget custom_code_tidestar_human_tidesclass_sub_f62f6792_fk_custom_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidestarget
    ADD CONSTRAINT custom_code_tidestar_human_tidesclass_sub_f62f6792_fk_custom_co FOREIGN KEY (human_tidesclass_subclass_id) REFERENCES public.custom_code_tidesclasssubclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_code_tidestarget custom_code_tidestar_tidesclass_subclass__08d60a8f_fk_custom_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_code_tidestarget
    ADD CONSTRAINT custom_code_tidestar_tidesclass_subclass__08d60a8f_fk_custom_co FOREIGN KEY (tidesclass_subclass_id) REFERENCES public.custom_code_tidesclasssubclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_comment_flags django_comment_flags_comment_id_d8054933_fk_django_comments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comment_flags
    ADD CONSTRAINT django_comment_flags_comment_id_d8054933_fk_django_comments_id FOREIGN KEY (comment_id) REFERENCES public.django_comments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_comment_flags django_comment_flags_user_id_f3f81f0a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comment_flags
    ADD CONSTRAINT django_comment_flags_user_id_f3f81f0a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_comments django_comments_content_type_id_c4afe962_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comments
    ADD CONSTRAINT django_comments_content_type_id_c4afe962_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_comments django_comments_site_id_9dcf666e_fk_django_site_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comments
    ADD CONSTRAINT django_comments_site_id_9dcf666e_fk_django_site_id FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_comments django_comments_user_id_a0a440a1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_comments
    ADD CONSTRAINT django_comments_user_id_a0a440a1_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_groupobjectpermission guardian_groupobject_content_type_id_7ade36b8_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobject_content_type_id_7ade36b8_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_groupobjectpermission guardian_groupobject_group_id_4bbbfb62_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobject_group_id_4bbbfb62_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_groupobjectpermission guardian_groupobject_permission_id_36572738_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobject_permission_id_36572738_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_userobjectpermission guardian_userobjectp_content_type_id_2e892405_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectp_content_type_id_2e892405_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_userobjectpermission guardian_userobjectp_permission_id_71807bfc_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectp_permission_id_71807bfc_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_userobjectpermission guardian_userobjectpermission_user_id_d5c1e964_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectpermission_user_id_d5c1e964_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_common_profile tom_common_profile_user_id_b182350f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_common_profile
    ADD CONSTRAINT tom_common_profile_user_id_b182350f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_dataproduct_group tom_dataproducts_dat_dataproduct_id_530f0f37_fk_tom_datap; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct_group
    ADD CONSTRAINT tom_dataproducts_dat_dataproduct_id_530f0f37_fk_tom_datap FOREIGN KEY (dataproduct_id) REFERENCES public.tom_dataproducts_dataproduct(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_dataproduct_group tom_dataproducts_dat_dataproductgroup_id_75dd81e2_fk_tom_datap; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct_group
    ADD CONSTRAINT tom_dataproducts_dat_dataproductgroup_id_75dd81e2_fk_tom_datap FOREIGN KEY (dataproductgroup_id) REFERENCES public.tom_dataproducts_dataproductgroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_dataproduct tom_dataproducts_dat_observation_record_i_95bdba8b_fk_tom_obser; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct
    ADD CONSTRAINT tom_dataproducts_dat_observation_record_i_95bdba8b_fk_tom_obser FOREIGN KEY (observation_record_id) REFERENCES public.tom_observations_observationrecord(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_dataproduct tom_dataproducts_dat_target_id_dce26955_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_dataproduct
    ADD CONSTRAINT tom_dataproducts_dat_target_id_dce26955_fk_tom_targe FOREIGN KEY (target_id) REFERENCES public.tom_targets_basetarget(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_reduceddatum_message tom_dataproducts_red_alertstreammessage_i_516add5f_fk_tom_alert; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_reduceddatum_message
    ADD CONSTRAINT tom_dataproducts_red_alertstreammessage_i_516add5f_fk_tom_alert FOREIGN KEY (alertstreammessage_id) REFERENCES public.tom_alerts_alertstreammessage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_reduceddatum tom_dataproducts_red_data_product_id_714545fa_fk_tom_datap; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_reduceddatum
    ADD CONSTRAINT tom_dataproducts_red_data_product_id_714545fa_fk_tom_datap FOREIGN KEY (data_product_id) REFERENCES public.tom_dataproducts_dataproduct(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_reduceddatum_message tom_dataproducts_red_reduceddatum_id_c9d20296_fk_tom_datap; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_reduceddatum_message
    ADD CONSTRAINT tom_dataproducts_red_reduceddatum_id_c9d20296_fk_tom_datap FOREIGN KEY (reduceddatum_id) REFERENCES public.tom_dataproducts_reduceddatum(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_dataproducts_reduceddatum tom_dataproducts_red_target_id_7112fa36_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_dataproducts_reduceddatum
    ADD CONSTRAINT tom_dataproducts_red_target_id_7112fa36_fk_tom_targe FOREIGN KEY (target_id) REFERENCES public.tom_targets_basetarget(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_observations_dynamiccadence tom_observations_dyn_observation_group_id_178fcf19_fk_tom_obser; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_dynamiccadence
    ADD CONSTRAINT tom_observations_dyn_observation_group_id_178fcf19_fk_tom_obser FOREIGN KEY (observation_group_id) REFERENCES public.tom_observations_observationgroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_observations_observationgroup_observation_records tom_observations_obs_observationgroup_id_1decf344_fk_tom_obser; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationgroup_observation_records
    ADD CONSTRAINT tom_observations_obs_observationgroup_id_1decf344_fk_tom_obser FOREIGN KEY (observationgroup_id) REFERENCES public.tom_observations_observationgroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_observations_observationgroup_observation_records tom_observations_obs_observationrecord_id_8e121c87_fk_tom_obser; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationgroup_observation_records
    ADD CONSTRAINT tom_observations_obs_observationrecord_id_8e121c87_fk_tom_obser FOREIGN KEY (observationrecord_id) REFERENCES public.tom_observations_observationrecord(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_observations_observationrecord tom_observations_obs_target_id_6e7111f2_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationrecord
    ADD CONSTRAINT tom_observations_obs_target_id_6e7111f2_fk_tom_targe FOREIGN KEY (target_id) REFERENCES public.tom_targets_basetarget(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_observations_observationrecord tom_observations_obs_user_id_517144d8_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_observations_observationrecord
    ADD CONSTRAINT tom_observations_obs_user_id_517144d8_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_targets_targetextra tom_targets_targetex_target_id_c59c68fc_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetextra
    ADD CONSTRAINT tom_targets_targetex_target_id_c59c68fc_fk_tom_targe FOREIGN KEY (target_id) REFERENCES public.tom_targets_basetarget(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_targets_targetlist_targets tom_targets_targetli_basetarget_id_4c3ed45a_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetlist_targets
    ADD CONSTRAINT tom_targets_targetli_basetarget_id_4c3ed45a_fk_tom_targe FOREIGN KEY (basetarget_id) REFERENCES public.tom_targets_basetarget(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_targets_targetlist_targets tom_targets_targetli_targetlist_id_41810969_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetlist_targets
    ADD CONSTRAINT tom_targets_targetli_targetlist_id_41810969_fk_tom_targe FOREIGN KEY (targetlist_id) REFERENCES public.tom_targets_targetlist(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tom_targets_targetname tom_targets_targetna_target_id_c5dda20c_fk_tom_targe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tom_targets_targetname
    ADD CONSTRAINT tom_targets_targetna_target_id_c5dda20c_fk_tom_targe FOREIGN KEY (target_id) REFERENCES public.tom_targets_basetarget(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

